// Solution:


fn main() {
    let v = {
        let x = 3;
        x
    };
 
    assert!(v == 3);
    println!("Success!");
 }
 

/* 
Explantion/What I understood:
x needs to be added to the main function to avoid the error.

*/